### ISSUE TITLE
Improvement suggestion: Localization

### ISSUE THREAD

**Issue by delta-kor** [katsukixyz/izone-archive#4]
Thank you so much for the work.

As iz\*ark google drive storage (iz\*one archive drive) was suspended in 2022, many korean fans has not been able to stream & watch the deleted videos that are not shared on the public (deleted vlive, etc.).
Many people are looking for alternative sites, but it's hard to come forward with huge operating expenses.
Although some koreans know this application, but still, most of them are having trouble with language problems.

We sincerely ask to build a basic localization system (UI menu, tags, titles transition).
If there's anything we can help with translation & system development, we'll help you.

**Comment by katsukixyz** [comment]
Thank you for the feedback. I will be begin working on internationalization/localization. Who should I reach out to regarding translation?

**Comment by delta-kor** [comment]
If you don't mind, I would help on the korean translation.

**Comment by katsukixyz** [comment]
@delta-kor Please see the mentioned PR for further details. I have built out a localization framework that requires rewriting in Korean the values for each key in the JSON files.

**Comment by delta-kor** [comment]
Thank you for the acception
